# Load necessary libraries
library(openxlsx)
library(R.utils)
library(tcltk)
library(limma)
library(pheatmap)
library(RColorBrewer)
library(gridExtra)
library(sva)
library(dplyr)
library(oligo)
library(GEOquery)
library(affy)
library(affyio)
library(hgu133a.db)
library(hgu133plus2.db)
library(AnnotationDbi)
library(grid)
library(ggplot2)
library(ggrepel)
library(clusterProfiler)
library(org.Hs.eg.db)
library(enrichplot)
library(GSVA)
library(GSEABase)
library(msigdbr)
library(DOSE)
library(WGCNA)
library(flashClust)
library(VennDiagram)
library(glmnet)
library(caret)
library(e1071)
library(randomForest)
library(rms)
library(pROC)
library(rmda)
library(cowplot)
library(patchwork)
library(plumber)


#import custom-made script with functions
source("D:/Master Thesis Bioinformatics/Code/GEO_lib_functions.R")
source("D:/Master Thesis Bioinformatics/Code/graph_functions.R")

